### ISSUE TITLE
Disable tabs when moving back

### ISSUE THREAD

**Issue by paulo-raca** [rstaib/jquery-steps#109]
On my application, the options available on each tab depends on what you have selected in the previous steps.

Out-of-the-box, JQuery steps allows us to move all the way to step 3, click back on step 1 (That's nice), change something (That ok too) and click back on step 3 (Ooops, you should have changed the options on step 2!).

Can we add a public function to manage enabled steps?
At the bare minimum, I need a function to disable all steps after the current one

**Comment by simondotwhite** [comment]
+1 please

**Comment by nickrobarov** [comment]
Add the following code in the onStepChanged Event Setting:

```
onStepChanged: function () {
      $('.steps .current').nextAll().removeClass('done').addClass('disabled');
}
```

**Comment by paulo-raca** [comment]
I think this should be part of the API, but the solution given has been  working for me for over a year.
Closing it
