### ISSUE TITLE
How do I store form data to session on clicking next?

### ISSUE THREAD

**Issue by abstractindia** [rstaib/jquery-steps#165]
I have a long form spanning in 12 steps. I want to store form data to session when the user clicks the next button. I am using the saveState which only remembers the step number and not the data. Please guide me.

**Comment by alopez18** [comment]
You can use http://malsup.com/jquery/form/#api with the formSerialize method...

**Comment by abstractindia** [comment]
Sorry @alopez18 ! I did not get it. How can it be done?

**Comment by alopez18** [comment]
Maibe yo can do this (http://stackoverflow.com/questions/1184624/convert-form-data-to-javascript-object-with-jquery) to serialize form a then do a loop in the json to deseralize. 
You can save the serialized string with many methods. 

You can send the inputs to the server with the forms in every **onStepChanging**.

``` javascript
 onStepChanging: function (event, currentIndex, newIndex) {
            if (wizardEncuesta.esperandoConsejos) {
                wizardEncuesta.esperandoConsejos = false;
                return true;
            } else {
                var $bodyCurrent = $(".body-wizard.body.current");
                var $form = $("form", $bodyCurrent);
                wizardEncuesta.$validator = null;
                wizardEncuesta.$validator = $form.validate({
                    errorPlacement: function ($error, $element) {
                        $element.parent().prepend($error);
                    }
                }).settings.ignore = ":disabled";
                if ($form.valid()) {
                    $bodyCurrent.prepend(gl.conf.spinnerAbsMaxHtml);
                    wizardEncuesta.esperandoConsejos = true
                    $form.submit();
                    return false;
                } else {
                    return false;
                }
            }
        },
```

**Comment by abstractindia** [comment]
Thanks for helping but I do not understand anything. Basically, I am a designer and I don't understand json. Is there a simple solution in php?

**Comment by alopez18** [comment]
I'm sorry but I don't have knowledge in php.
If you need to save the state of the form in every step change you have to serialize the form and then do a populate from the serialized form to the html form.

I can't help you more, Sorry.
