### ISSUE TITLE
Submitting every step with multiple forms

### ISSUE THREAD

**Issue by fatagun** [rstaib/jquery-steps#166]
Hello,

I want to have steps. Then I want the steps to have different forms, everytime step changes, with previous or next buttons, I d like to submit the form. 

When i tried with multiple forms, it didnt work, cause `var form = $("#example-advanced-form").show();` 
so i guess i cant use multiple forms?

Does that mean, I should submit the whole form everytime I change a step? Well i cant really do that, because in different steps there are validation rules on server side. 

Can you help me out?

**Comment by webinformat** [comment]
I know this question is old but I just had some similar requirements and I made a codepen 
https://codepen.io/ciprianz/pen/bMBeBL
