### ISSUE TITLE
not working when adding runat="server" to form

### ISSUE THREAD

**Issue by wilaponce** [rstaib/jquery-steps#173]
I have an asp.net site and I need to add runat=server to form and when I do, it does not render correctly.

<form id="example" runat="server" action="#">
    <div>
        <h3>Account</h3>
        <section>
          Something here....
        </section>
    <div>
</form>

![image](https://cloud.githubusercontent.com/assets/7507770/11908258/7a62967a-a58f-11e5-9580-001faeac007d.png)

**Comment by AmineHamrouni** [comment]
Did you find a solution??
