### ISSUE TITLE
can i add nested wizards?

### ISSUE THREAD

**Issue by oterox** [rstaib/jquery-steps#23]
I need nested wizards, is this possible?

And is it possible that the nested wizard is dynamic, i mean:

main wizard: step1 | step2 | step3

then, step 2 would have a nested wizard inside like subtab1 | subtab2 ...
This substeps would be created dinamically in step1 but instead of being added to the main wizard they would be added to nested wizard, like this:
![wizard](https://f.cloud.github.com/assets/1680006/1574334/4b67b426-513c-11e3-8068-3e9df8f48d75.jpg)

I've readed the doc and i can add tabs dinamically, but i can't find anything about nested ones.

**Comment by jharahul** [comment]
Has this been merged into master so that its available in latest version download ?

**Comment by ivisionwd** [comment]
Has this been merged into master so that its available in latest version download ? Can we get a demo?

**Comment by n0tel** [comment]
@grandstylus16 this example does not work?
https://jsfiddle.net/7jkt6/6/

**Comment by ivisionwd** [comment]
it works but I wanted for the nested step to work with the main step previous/next button and also to not show a second pagination header and when I go to the next main step and click on previous to to go back to the last nested step of the previous main step the content disappears

**Comment by n0tel** [comment]
You can check current step on `onStepChanged` for nested wizard. And if
true, process it.

You can disable pagination, see options.

On Thursday, August 20, 2015, grandstylus16 notifications@github.com
wrote:

> it works but I wanted for the nested step to work with the main step
> previous/next button and also to not show a second pagination header
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/rstaib/jquery-steps/issues/23#issuecomment-132793033.

## 

С уважением,
Хандрамай Павел Александрович
