### ISSUE TITLE
plugin is not working on safari 11.1

### ISSUE THREAD

**Issue by prietoedgardo** [rstaib/jquery-steps#257]
Hello to all!

Currently im using this plugin on my webiste, and was working on all known browsers and previous versions of safari, but last update (11.1) is having issues with the plugin, anyone have the same problem? there is a workaround? thank you in advance!

**Comment by rstaib** [comment]
If you are going [here](http://www.jquery-steps.com/Examples), are those Example working?

**Comment by mltgroup** [comment]
I also noticed an issue on the safari 11. When Step contents are loading through AJAX then the whole wizard is broken.

**Comment by mushi-iqbal** [comment]
I also noticed an issue on the safari 11.1 especially when Step contents are loading through AJAX then the whole wizard is broken.

**Comment by prietoedgardo** [comment]
hello again!

I fixed the problem, is the same problem detailed here:

https://github.com/rstaib/jquery-steps/issues/242

Thank you!

**Comment by mushi-iqbal** [comment]
@prietoedgardo Can you please help me how to fix this issue?

**Comment by prietoedgardo** [comment]
check this other issue: https://github.com/rstaib/jquery-steps/issues/242... i fixed in the same way.

**Comment by rstaib** [comment]
This issue is a duplicate. Please see here #242.

**Comment by mushi-iqbal** [comment]
@prietoedgardo My HTML also contain currency sign like US dollar $ and due to this steps are broken.
Same like this https://user-images.githubusercontent.com/5252612/39056172-8c4777ce-447b-11e8-87c6-d981b8814fb3.png
Can you tell me where to apply fix. Thanks
