### ISSUE TITLE
Conflict with many js  plugins

### ISSUE THREAD

**Issue by xumoqiu** [rstaib/jquery-steps#300]
like select2，datetimepicker and so on

**Comment by vutran0111** [comment]
The same problem :( 
@xumoqiu Did you find out a solution to the problem?

**Comment by ronaklalwaniii** [comment]
+1

**Comment by xumoqiu** [comment]
其它插件必须初始化jquery-steps之后调用 就好了 @Tranxuanvu

**Comment by vutran0111** [comment]
> 其它插件必须初始化jquery-steps之后调用 就好了 @Tranxuanvu

I've removed this plugin in and use another way to implement 😄
Thanks for your reply, bro!

**Comment by ronaklalwaniii** [comment]
Hi, after hours of trying I ended up creating a different file for all the other plugins. 

This separate file load after the file in which I initialized steps.

Hope this helps.

Cheers ~
