### ISSUE TITLE
Lack of data submission

### ISSUE THREAD

**Issue by elroyshilling** [rstaib/jquery-steps#55]
One of the most fundamental reasons for having forms is to collect data. This wizard lacks those very fundamentals. 

Server-side examples are none existent, PHP form submission should at least be in the documents - Or so I think.

Tried to use <?php echo $PHP_SELF;?> the only way is to hack the script to have a custom type="submit" button. Time to move back to the old and trusted wizards.

**Comment by TheBigK** [comment]
@rstaib and @elroyshilling - I'm loving this plugin but really stuck with the right approach to submit the data collected using the Wizard. 

Questions: Is form.submit() safe? If not, what kind of problems can it cause? I looked up lot of information but could not arrive at a conclusion.

Will this be a better approach to submit the data once the user is on the last step of the wizard: 

$('#submit_btn').click(function() {
   $.ajax({
          type: "POST",
          url: "/your/page",
          data: jsonData,
          contentType:'application/json',
          processData: false,  
          error: function(response) {console.log('ERROR '+Object.keys(response)); },
          success: function(response) { console.log('SuCCESS'+Object.keys(response));
});
