### ISSUE TITLE
Dynamic height

### ISSUE THREAD

**Issue by maxtac** [rstaib/jquery-steps#8]
Hello, and congratulations for your work.

It is possible to make sure that the height of the "content" adapts automatically to its content?
Maybe setting a minimum height, below which one should not go down, and then doing so that the height of the content increases in case there is a very long content.

I used your script, but in some steps of the wizard I have a content too long, which consequently is not shown

Thanks

**Comment by derekrivers** [comment]
Has anyone came across an issue with using the Compare Data Annotation with JQuery Steps?

It basically stops working in my app when i use it with a form hooked up to JQuery steps.

I'm using it when validating two email addresses that need to match,  I've tried running the same app, with & without the inclusion of Jquery Steps, and the result  differs.

Any Ideas?

**Comment by bhanutadinada** [comment]
I have this function which I call on each step change. Posting here so it could help someone while @rstaib is working on the enhancement:

``` javascript
//This is the function I call in the onstepchanged event
function adjustStepHeight(){
  sum = 0;
  //get the current step number
  stepNumber = $("#my-form").steps("getCurrentIndex");
  //get the combined height of all child elements in the step
  $("#my-form-p-"+stepNumber).children().each(function(){
       sum += ($(this).height()+
                     parseInt($(this).css("margin-top"))+
                     parseInt($(this).css("margin-bottom"))
  )});

  //add vertical padding to the sum variable
  sum += (parseInt($("#my-form-p-"+stepNumber).css("padding-top")))*2;

  //set height of step to the sum value 
  $(".wizard > .content").css("height",sum); 
}
```

I call this on the onstepchanged event like below:

``` javascript
onStepChanged:function (event, currentIndex, priorIndex) {
adjustStepHeight();
}
```

edit on 01.15.2015 per @devkinetic 's suggestion - Thanks for posting your edit man.

also set:

```
.wizard .content {
  min-height: 0;
}
.wizard > .content > .body {
height: auto;
}
```

**Comment by kenjaw** [comment]
I used the @rherring solution, but it appears to only scale upon first rendering the step.  I have a step where someone has an option to show hidden divs that expand the content, but it appears that jquery steps does not resize dynamically when that happens via a javascript call.  Is there a function I can call to have the step resize after I show the hidden divs?  Thanks!  Great plugin!

**Comment by bhanutadinada** [comment]
@kenjaw you could do what I did in my example above. Just call teh adjustStepHeight function after you show the divs.

Updated formatting for better readability.

**Comment by devkinetic** [comment]
@helius06 your solution worked for me. I added your function and called it in both onInit and onStepChanged. It should also be noted that you need to set:

``` css
.wizard .content {
  min-height: 0;
}
.wizard > .content > .body {
height: auto;
}
```

I hope this issue gets addressed.

**Comment by msalsas** [comment]
This solution has worked for me. [http://formvalidation.io/examples/jquery-steps/](http://formvalidation.io/examples/jquery-steps/) 
Just CSS

```
.wizard .content {
    min-height: 100px;
}
.wizard .content > .body {
    width: 100%;
    height: auto;
    padding: 15px;
    position: relative;
}
```

**Comment by Arkaniad** [comment]
@msalsas your solution worked PERFECTLY! Thank you! Very happy to not have to add any more Javascript here.

**Comment by TheBokiya** [comment]
@msalsas solution works great but do note that `slideLeft` transition becomes buggy with that CSS overwrite.

**Comment by SeunMatt** [comment]
@hbbh solution works for me. 

145: min-height: 35em; //this can be found in .wizard > .content 
168: height: 95%; //this can be found in .wizard > .content > .body 

so take note of the locations in the jquery-steps.css file.

**Comment by BlueSky1021** [comment]
anyone with the best answer so far??

**Comment by dustinparker** [comment]
I tried @msalsas solution and adjusted the css to the following and it seems to be working smoother for the slideLeft transition:

```
.wizard .content {
    min-height: 100px;
}
.wizard .content > .body {
    width: 100%;
    height: auto;
    padding: 15px;
    position: absolute;
}
.wizard .content .body.current {
    position: relative;
}
```

**Comment by mohamedali0887** [comment]
I tried 

> .wizard .content {
>     min-height: auto;
> }

and it worked fine for me.

**Comment by aalok125** [comment]
> I tried @msalsas solution and adjusted the css to the following and it seems to be working smoother for the slideLeft transition:
> 
> ```
> .wizard .content {
>     min-height: 100px;
> }
> .wizard .content > .body {
>     width: 100%;
>     height: auto;
>     padding: 15px;
>     position: absolute;
> }
> .wizard .content .body.current {
>     position: relative;
> }
> ```

It Works for me too thanks

**Comment by zandiarash** [comment]
Thanks @msalsas and @aalok125
You solved my problem.
Very big up to you.

**Comment by arissupriy** [comment]
> I tried overflow-y: auto;
> 
> But I got a scroller. Is it possible to adjust the height according to the content instead of a scroller?
> The scroller don't work well in mobile.
> 
> I tried height: auto; for .wizard>.content and/or .wizard > .content > .body > iframe
> 
> The content only overflow slightly but the height still did not cover the whole content.
> 
> Please advise. Hope to hear from you soon. Thanks :)

worked fine for me : 
```
.wizard> .content > .body {
            position: relative;
        }
```

**Comment by Sudo255** [comment]
I am using _**jquery.step.css**_ version v1.0.6
.wizard > .content
{
    background: #eee;
    display: block;
    margin: 5px 5px 10px 5px;
    /*min-height: 120px;*/
    **min-height: 0;** 
    overflow: hidden;
    position: relative;
    width: auto;
    -webkit-border-radius: 5px;
    -moz-border-radius: 5px;
    border-radius: 5px;
}
.wizard > .content > .body
{
    float: left;
    position: absolute;
    width: 95%;
    /*height: 95%;*/
    **height: auto;**
    padding: 2.5%;
}

I appreciate everyone who contributed to this solution

**Comment by douglas-88** [comment]
> This solution has worked for me. http://formvalidation.io/examples/jquery-steps/
> Just CSS
> 
> ```
> .wizard .content {
>     min-height: 100px;
> }
> .wizard .content > .body {
>     width: 100%;
>     height: auto;
>     padding: 15px;
>     position: relative;
> }
> ```

It worked perfectly for me.
Thank you very much.
