### ISSUE TITLE
datepicker is not working

### ISSUE THREAD

**Issue by prakashkolandaivelu** [rstaib/jquery-steps#85]
Hey, i added a datepicker inthe panel. it is not working. actually on focus, it shoyuld show up a pop up to choose the date. But i am not getting the pop up. am i missign something plz advice

**Comment by atahualpasf** [comment]
Hey sorry I have the same problem. How did you solve yours¿? @rstaib @pkolanda 
The link is not working.

**Comment by NabeelYousafPasha** [comment]
Hi @rstaib @pkolanda please write the solution down here. because JsFiddle is not opening tab.
Thanks in advance

**Comment by minirai** [comment]
Hi @rstaib @pkolanda please write the solution down here. JsFiddle is not opening.
