### ISSUE TITLE
saveState() is not working 

### ISSUE THREAD

**Issue by sravanthim** [rstaib/jquery-steps#86]
i set saveState() to true on steps wizard. but, its not saving any cookies to the browser and isn't saving last selected active tab on postback

**Comment by abstractindia** [comment]
saveState is not working, I checked even by adding saveState: true in your demo/index file. But not working. The jQuery.cookie (version 1.3.1) is already included. 
I want to retain the step the user is on, if by mistake or for any other reason he hits refresh. I don't know how to accomplish this. Please check the screenshot
![screen000](https://cloud.githubusercontent.com/assets/14857472/10121689/655ee95e-6516-11e5-9b7b-a5f9e6fadb46.jpg)

**Comment by sentisoft** [comment]
I try this also.. for me its save step.. if I on step number 2 it will load step 2 after refresh, but the problem is that all inputs on step 1 is refreshed and deleted.. this is not good :( I added jquery.cookie.js an have this ins script saveState: true .. do I need add something else?

**Comment by sentisoft** [comment]
I try to add this in my custom js $.cookie('name', 'value'); but this not help.. I have for example input <input type="text" id="first-name" class="required" size="40" value="" name="first-name"> how to add this to cookie?
