### ISSUE TITLE
Focus on first element of current step when changing steps

### ISSUE THREAD

**Issue by vierkantemeter** [rstaib/jquery-steps#91]
I'm trying to give focus to the first form field on the current step when changing steps. As a default, the focus is on the step button, how can I change it to focus the first form field?

I tried:

```
onStepChanged: function (event, currentIndex, priorIndex)
{     
    $('#wizard .content :input:enabled:visible:first').focus();
}
```

but this isn't working unfortunately. Is this possible to accomplish?

**Comment by Luizgpp** [comment]
Reviving topic, i'm still get this issue.

autofocus on input not work.
