### ISSUE TITLE
Get the current step onLoad

### ISSUE THREAD

**Issue by lakshmilanka** [rstaib/jquery-steps#95]
Hello,

I've my "saveState" property set true. And I'm loading my steps only when the user clicks on "Prev" or "Next" button. In this case, how do I know which steps is currently active on the page load so that I can only load that particular step?

Not sure if this has been already addressed. Any help is greatly appreciated.

**Comment by pfhenley86** [comment]
Hey I know this is closed but the documentation doesn't seem to straight forward. Do you have any example code of how you got it to work or where I can learn about the built in async functionality.
