### ISSUE TITLE
Styling the 'Step' titles

### ISSUE THREAD

**Issue by Jericho** [rstaib/jquery-steps#98]
Is there any way to change the style of the step titles? 

For instance, is it possible to display them in a way where each step looks like an arrow pointing to the next title similar to: http://css-tricks.com/triangle-breadcrumbs/. It would be great if there was a few styles to chose from.

Also, is it possible to completely hide the titles?

**Comment by drmcclelland** [comment]
@Jericho - if by "completely hide the titles" you mean to hide the tabs across the top, you can use this approach suggested in #16
